# Generated by Django 5.0.7 on 2024-07-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_geo',
            field=models.DateField(null=True),
        ),
    ]
