# Generated by Django 5.0.7 on 2024-07-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_date_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_geo',
        ),
    ]
