# Generated by Django 5.0.1 on 2024-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_date_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
