# Generated by Django 5.0.7 on 2024-07-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_table_capacity_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
